### ISSUE TITLE
Don't export ~> from Ruby

### ISSUE THREAD

**Issue by calebhearth** [dependent/dependencies#5]
The `~>` operator is confusing to beginners+, and is less expressive and powerful than only using <, >, <=, and >=. I propose:

``` yaml
ruby: ">= 2.3", "< 3", file: "Gemfile" # Equivalent, maybe, to ~> 2.3
postgres: "9.3" # 9.3 exactly
python: "> 2.7", file: "requirements.txt" # more than 2.7
node: "< 6", file: "package.json" # Any version, so long as it's less than 6
```
