### ISSUE TITLE
Use resolvers rather than languages

### ISSUE THREAD

**Issue by calebhearth** [dependent/dependencies#6]
Some languages have multiple resolvers, and this allows "postgres" to make more sense as everything listed is something we have as a dependency.

``` yaml
gem: "~> 2.3", file: "Gemfile"
postgres: "~> 9.3"
pip: "~> 2.7", file: "requirements.txt"
npm: "~> 5.5", file: "package.json"
```

Better yet, make every "key" something that needs to be in PATH (which simplifies implementations somewhat):

``` yaml
psql: "~> 9.3"
```
